
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  config:
    activate:
      on-profile: local

  application:
    name: julindang-gateway
  devtools:
    livereload:
      enabled: true
  cloud:
    gateway:
      enabled: true
      routes:
        - id: no-authority
          uri: lb://MEMBER
          predicates:
            - Path=/token/**, /member/sign-up, /member/verify, /member/swagger-ui.html, /member/nickname

        - id: no-authority1
          uri: lb://CAFE
          predicates:
            - Path=/cafe/find-by-cafe-name-and-beverage-name, /cafe/find-by-cafe-name, /cafe/find-by-beverage-name

        - id: etc
          uri: lb://MEMBER
          predicates:
            - Path=/etc/**

        - id: sms
          uri: lb://MEMBER
          predicates:
            - Path=/sms/**

        - id: consume
          uri: lb://CONSUME
          predicates:
            - Path=/consume/**

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/member/sign-up, /member/nickname, /member/login, /auth/check, /token/**
          filters:
            - JwtUserFilter

        - id: cafe
          uri: lb://CAFE
          predicates:
            - Path=/cafe/save, /cafe/delete
          filters:
            - JwtAdminFilter

        - id: member-admin
          uri: lb://MEMBER
          predicates:
            - Path=/member/**, /auth/**
          filters:
            - JwtAdminFilter

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway=ERROR:

gateway:
  host: http://127.0.0.1:8081/auth/check