
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}/eureka
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS}
spring:
  application:
    name: julindang-gateway
  devtools:
    livereload:
      enabled: true
  cloud:
    gateway:
      enabled: true
      routes:
        - id: no-authority
          uri: lb://MEMBER
          predicates:
            - Path=/token/**, /member/sign-up, /member/verify, /member/swagger-ui.html, /member/nickname

        - id: no-authority1
          uri: lb://CAFE
          predicates:
            - Path=/cafe/find-by-cafe-name-and-beverage-name, /cafe/find-by-cafe-name, /cafe/find-by-beverage-name

        - id: etc
          uri: lb://MEMBER
          predicates:
            - Path=/etc/diabetes/**

        - id: sms
          uri: lb://MEMBER
          predicates:
            - Path=/sms/**

        - id: consume
          uri: lb://CONSUME
          predicates:
            - Path=/consume/**
          filters:
            - JwtUserFilter

        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/member/sign-up, /member/nickname, /member/login, /auth/check, /token/**
          filters:
            - JwtUserFilter

        - id: cafe
          uri: lb://CAFE
          predicates:
            - Path=/cafe/save, /cafe/delete
          filters:
            - JwtAdminFilter

        - id: member-admin
          uri: lb://MEMBER
          predicates:
            - Path=/auth/**, /member-admin/**
          filters:
            - JwtAdminFilter

        - id: consume-admin
          uri: lb://CONSUME
          predicates:
            - Path=/consume-admin/**
          filters:
            - JwtAdminFilter

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway=ERROR:

gateway:
  host: ${GATEWAY_URL}